In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

In [ ]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [ ]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

In [ ]:
print(t.word_index)

In [ ]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

In [ ]:
print(sequences)

In [ ]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

In [ ]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [ ]:
print(sequences)

In [ ]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [ ]:
print(X)

In [ ]:
print(y)

In [ ]:
y = to_categorical(y, num_classes=vocab_size)

In [18]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [22]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4569 - accuracy: 0.0909
Epoch 2/200
1/1 - 0s - loss: 2.4438 - accuracy: 0.0000e+00
Epoch 3/200
1/1 - 0s - loss: 2.4305 - accuracy: 0.1818
Epoch 4/200
1/1 - 0s - loss: 2.4168 - accuracy: 0.1818
Epoch 5/200
1/1 - 0s - loss: 2.4028 - accuracy: 0.2727
Epoch 6/200
1/1 - 0s - loss: 2.3882 - accuracy: 0.2727
Epoch 7/200
1/1 - 0s - loss: 2.3732 - accuracy: 0.2727
Epoch 8/200
1/1 - 0s - loss: 2.3575 - accuracy: 0.3636
Epoch 9/200
1/1 - 0s - loss: 2.3413 - accuracy: 0.3636
Epoch 10/200
1/1 - 0s - loss: 2.3243 - accuracy: 0.3636
Epoch 11/200
1/1 - 0s - loss: 2.3066 - accuracy: 0.3636
Epoch 12/200
1/1 - 0s - loss: 2.2882 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.2690 - accuracy: 0.4545
Epoch 14/200
1/1 - 0s - loss: 2.2491 - accuracy: 0.4545
Epoch 15/200
1/1 - 0s - loss: 2.2285 - accuracy: 0.4545
Epoch 16/200
1/1 - 0s - loss: 2.2072 - accuracy: 0.4545
Epoch 17/200
1/1 - 0s - loss: 2.1852 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.1628 - accuracy: 0.36

Epoch 147/200
1/1 - 0s - loss: 0.3185 - accuracy: 0.9091
Epoch 148/200
1/1 - 0s - loss: 0.3123 - accuracy: 0.9091
Epoch 149/200
1/1 - 0s - loss: 0.3061 - accuracy: 0.9091
Epoch 150/200
1/1 - 0s - loss: 0.3002 - accuracy: 0.9091
Epoch 151/200
1/1 - 0s - loss: 0.2943 - accuracy: 1.0000
Epoch 152/200
1/1 - 0s - loss: 0.2886 - accuracy: 1.0000
Epoch 153/200
1/1 - 0s - loss: 0.2830 - accuracy: 1.0000
Epoch 154/200
1/1 - 0s - loss: 0.2776 - accuracy: 1.0000
Epoch 155/200
1/1 - 0s - loss: 0.2722 - accuracy: 1.0000
Epoch 156/200
1/1 - 0s - loss: 0.2670 - accuracy: 1.0000
Epoch 157/200
1/1 - 0s - loss: 0.2619 - accuracy: 1.0000
Epoch 158/200
1/1 - 0s - loss: 0.2569 - accuracy: 1.0000
Epoch 159/200
1/1 - 0s - loss: 0.2520 - accuracy: 1.0000
Epoch 160/200
1/1 - 0s - loss: 0.2472 - accuracy: 1.0000
Epoch 161/200
1/1 - 0s - loss: 0.2426 - accuracy: 1.0000
Epoch 162/200
1/1 - 0s - loss: 0.2380 - accuracy: 1.0000
Epoch 163/200
1/1 - 0s - loss: 0.2336 - accuracy: 1.0000
Epoch 164/200
1/1 - 0s - loss: 

In [23]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' '+ word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [24]:
print(sentence_generation(model, t, '경마장에', 4))

경마장에 있는 말이 뛰고 있다


C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [25]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


In [26]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오는 말이 곱다


In [27]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [29]:
df=pd.read_csv('ArticlesApril2018.csv')
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [30]:
print('열의 개수: ', len(df.columns))
print(df.columns)

열의 개수:  15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [31]:
df['headline'].isnull().values.any()

False

In [32]:
headline = []
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [33]:
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [34]:
headline = [n for n in headline if n != "Unknown"]
print('노이즈값 제거 후 샘플의 개수 : {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수 : 1214


In [35]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [36]:
def repreprocessing(s):
    s=s.encode("utf8").decode("ascii", 'ignore')
    return "".join(c for c in s if c not in punctuation).lower()

text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [37]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [39]:
sequences = list()

for line in text:
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [40]:
index_to_word={}
for key, value in t.word_index.items():
    index_to_word[value] = key
    
print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : offer


In [41]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [42]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [43]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [44]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [45]:
print(y[:3])

[ 269  371 1115]


In [46]:
y = to_categorical(y, num_classes=vocab_size)

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [49]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
244/244 - 4s - loss: 7.6484 - accuracy: 0.0276
Epoch 2/200
244/244 - 3s - loss: 7.1207 - accuracy: 0.0293
Epoch 3/200
244/244 - 3s - loss: 6.9902 - accuracy: 0.0323
Epoch 4/200
244/244 - 3s - loss: 6.8728 - accuracy: 0.0379
Epoch 5/200
244/244 - 3s - loss: 6.7944 - accuracy: 0.0413
Epoch 6/200
244/244 - 3s - loss: 6.6019 - accuracy: 0.0455
Epoch 7/200
244/244 - 3s - loss: 6.4483 - accuracy: 0.0440
Epoch 8/200
244/244 - 3s - loss: 6.2745 - accuracy: 0.0525
Epoch 9/200
244/244 - 3s - loss: 6.0898 - accuracy: 0.0587
Epoch 10/200
244/244 - 3s - loss: 5.9047 - accuracy: 0.0625
Epoch 11/200
244/244 - 3s - loss: 5.7213 - accuracy: 0.0683
Epoch 12/200
244/244 - 3s - loss: 5.5460 - accuracy: 0.0730
Epoch 13/200
244/244 - 3s - loss: 5.3774 - accuracy: 0.0748
Epoch 14/200
244/244 - 3s - loss: 5.2170 - accuracy: 0.0804
Epoch 15/200
244/244 - 3s - loss: 5.0628 - accuracy: 0.0884
Epoch 16/200
244/244 - 3s - loss: 4.9143 - accuracy: 0.0986
Epoch 17/200
244/244 - 3s - loss: 4.7748 - accura

244/244 - 3s - loss: 0.3441 - accuracy: 0.9144
Epoch 138/200
244/244 - 3s - loss: 0.3460 - accuracy: 0.9149
Epoch 139/200
244/244 - 3s - loss: 0.3305 - accuracy: 0.9150
Epoch 140/200
244/244 - 3s - loss: 0.3269 - accuracy: 0.9150
Epoch 141/200
244/244 - 3s - loss: 0.3210 - accuracy: 0.9167
Epoch 142/200
244/244 - 3s - loss: 0.3177 - accuracy: 0.9167
Epoch 143/200
244/244 - 3s - loss: 0.3151 - accuracy: 0.9148
Epoch 144/200
244/244 - 3s - loss: 0.3138 - accuracy: 0.9152
Epoch 145/200
244/244 - 3s - loss: 0.3109 - accuracy: 0.9155
Epoch 146/200
244/244 - 3s - loss: 0.3092 - accuracy: 0.9159
Epoch 147/200
244/244 - 3s - loss: 0.3062 - accuracy: 0.9163
Epoch 148/200
244/244 - 3s - loss: 0.3053 - accuracy: 0.9171
Epoch 149/200
244/244 - 3s - loss: 0.3020 - accuracy: 0.9162
Epoch 150/200
244/244 - 3s - loss: 0.3014 - accuracy: 0.9175
Epoch 151/200
244/244 - 3s - loss: 0.3002 - accuracy: 0.9152
Epoch 152/200
244/244 - 3s - loss: 0.3030 - accuracy: 0.9162
Epoch 153/200
244/244 - 3s - loss: 0.3

In [54]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=23, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [55]:
print(sentence_generation(model, t, 'i', 10))

i cant jump ship from facebook yet sex with not it


In [56]:
print(sentence_generation(model, t, 'how', 10))

how to make facebook more accountable beat trump in you at
